// Generated by flute sync. Edit recipes and components, not this registry.
import recipe0 from "./scenes/library-reveal.scene.json";
export const sceneModules = {
  "src/flute/scenes/library-reveal.scene.json": async () => ({default:recipe0}),
  "src/flute/scenes/library-reveal.tsx": () => import("./scenes/library-reveal"),
};
